### ISSUE TITLE
Debian 9?

### ISSUE THREAD

**Issue by Varbin** [tatsushid/h2o-deb#2]
Debian 9 (Stretch) will release in 16 days (17th June 2017). 

How to build Debian packages of h2o for Debian 9?

**Comment by Varbin** [comment]
I can confirm that the Debian 8 packages works for the current prerelease of Debian 9.

**Comment by gi11es** [comment]
The sources for Debian stretch don't seem to work right now:

```
Reading package lists... Done
W: The repository 'http://dl.bintray.com/tatsushid/h2o-deb stretch-backports Release' does not have a Release file.
N: Data from such a repository can't be authenticated and is therefore potentially dangerous to use.
N: See apt-secure(8) manpage for repository creation and user configuration details.
E: Failed to fetch http://dl.bintray.com/tatsushid/h2o-deb/dists/stretch-backports/main/binary-amd64/Packages  404  Not Found
E: Some index files failed to download. They have been ignored, or old ones used instead.
gilles@browsertime:~$ sudo apt-get install h2o
Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Unable to locate package h2o
```

**Comment by Varbin** [comment]
I think there are no sources for h2o on bintray for Debian 9. Anyhow I  can confirm the Debian 8 packages still work on Debian 9.

**Comment by tatsushid** [comment]
I finally added Debian 9 package to Bintray. Please check it.

**Comment by Varbin** [comment]
Works!
![grafik](https://user-images.githubusercontent.com/5983372/27508176-04241a14-58e0-11e7-8311-4bfb087a8107.png)
![grafik](https://user-images.githubusercontent.com/5983372/27508166-e1584d34-58df-11e7-9d7b-69e79ad4a143.png)

Thank you.
